### PR TITLE
Us 6 for Tasks 18 and 19

### PR DESCRIPTION
**Pull request by jfjovel**
The pull request is to verify that the preferences dialog box does show now as well as the look and feel portions of it are no longer visible or usable.  The changes made to the files are written in the commit and commented on the files themselves.  I mistaken named the commits as task 1 and task 2 when they should have been task 18 and task 19.--jjovel1

### CODE REVIEW

**Comment by mville18** [comment]
I reviewed the code and see that it the "Look and Feel" was commented out. Don't forget the declarations as well. In PreferencesDialog.java, lines: 47, 49, 51, 53, 57. In case the lines don't line up:
	47. ButtonGroup lfGroup = new ButtonGroup();
	49. JRadioButton lfSystemRB = new JRadioButton();
	51. JRadioButton lfJavaRB = new JRadioButton();
	53. JRadioButton lfCustomRB = new JRadioButton();
	57. JTextField lfClassName = new JTextField();

It may be best to completely remove instead of commenting out. I am just thinking about it as it came from a US so the product owner will not want to add it later.

As far as the changes to MimeType.java, I see that you fixed the directory but it is not clear to me how it relates to the "Look and Feel" tasks. If not directly tied to it then, you should create and assign an additional task to get credit for it. If it doesn't fall within the same user story then try to fit in another. We cannot create new US unless we clear it with Dr. Mehlhase.

**Comment by jfjovel** [comment]
I have made the changes into the software and have deleted any information relating to look and feel.  Per a previous discussion, the changes in mimetype relate to getting the preferences popup to actually popup.  It was being held back by a wrong pathname.  There were no additional changes made to that.

**Comment by jfjovel** [comment]
The changes were made as discussed.  The file compiled without issue and the preferences individual functions work as designed.  No other errors show while preferences is in use. 

As a side we should look at the preferences for closing the file as it controls the issue that we have seen where the application continues to run even after hitting exit or the x.

**Comment by jfjovel** [comment]
committed again and added notes for changes.

**Pull request merged**
